FLOAT_DIMS = ("score","rank","zscore")

INPUT_DOMAINS = {
    "window":(5,10,20,60,120,240,720),
    "short_window":(5,10,20),
    "mid_window":(20,60,120),
    "long_window":(120,240,720),
    "quantile":(0.1,0.2,0.3,0.5,0.7,0.8,0.9),
    "adjust_ratio":(0.2,0.5,0.8),
    "power":(2,3),
    "rettype":(0,1,2,3),
    "bucket_count":(3,5,10),
    "alpha":(0.1,0.2,0.5,0.8),
    "cut_pool":("ret1","resret","to1","vol5","amplitude","pos_a","illiq1"),
    "fd_weight":(-1,0,1),
    "fd_method":("decay","mean"),
}

OPS_REGISTRY = {
    "math_self":{"factory":"math","inputs":("float",),"output":"same","directional":False,"order_preserving":True},
    "ts_self":{"factory":"ts","inputs":("float",),"output":"same","directional":False,"order_preserving":True},
    "group_self":{"factory":"group","inputs":("float",),"output":"same","directional":False,"order_preserving":True},

    "eq":{"factory":"condition","inputs":("float","float"),"output":"condition","directional":False,"order_preserving":False},
    "le":{"factory":"condition","inputs":("float","float"),"output":"condition","directional":True,"order_preserving":False},
    "ge":{"factory":"condition","inputs":("float","float"),"output":"condition","directional":True,"order_preserving":False},
    "con_and":{"factory":"condition","inputs":("condition","condition"),"output":"condition","directional":False,"order_preserving":False},
    "con_or":{"factory":"condition","inputs":("condition","condition"),"output":"condition","directional":False,"order_preserving":False},
    "con_not":{"factory":"condition","inputs":("condition",),"output":"condition","directional":False,"order_preserving":False},

    "bucket":{"factory":"group","inputs":("float","bucket_count"),"output":"group","directional":False,"order_preserving":False},
    "group_merge":{"factory":"group","inputs":("group","group"),"output":"group","directional":False,"order_preserving":False},

    "neg":{"factory":"math","inputs":("float",),"output":"same","directional":False,"order_preserving":True},
    "abs":{"factory":"math","inputs":("float",),"output":"same","directional":False,"order_preserving":False},
    "signal":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "power":{"factory":"math","inputs":("float","power"),"output":"score","directional":False,"order_preserving":False},
    "signed_power":{"factory":"math","inputs":("float","power"),"output":"score","directional":False,"order_preserving":True},
    "sqrt":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":True},
    "log":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":True},
    "diff":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "diff_q":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "tanh":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":True},
    "pos_part":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "neg_part":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "midmap":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "xlogx":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "leftmap":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "rightmap":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "extreme_leftmap":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},
    "extreme_rightmap":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":False},

    "cs_rank":{"factory":"math","inputs":("float",),"output":"rank","directional":False,"order_preserving":True},
    "cs_neutralize":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":True},
    "cs_zscore":{"factory":"math","inputs":("float",),"output":"zscore","directional":False,"order_preserving":True},
    "cs_weighted_zscore":{"factory":"math","inputs":("float","float"),"output":"zscore","directional":True,"order_preserving":True},
    "cs_scale":{"factory":"math","inputs":("float",),"output":"score","directional":False,"order_preserving":True},

    "group_rank":{"factory":"group","inputs":("float","group"),"output":"rank","directional":True,"order_preserving":False},
    "group_neutralize":{"factory":"group","inputs":("float","group"),"output":"score","directional":True,"order_preserving":False},
    "group_zscore":{"factory":"group","inputs":("float","group"),"output":"zscore","directional":True,"order_preserving":False},
    "group_scale":{"factory":"group","inputs":("float","group"),"output":"score","directional":True,"order_preserving":False},
    "group_midmap":{"factory":"group","inputs":("float","group"),"output":"score","directional":True,"order_preserving":False},
    "group_leftmap":{"factory":"group","inputs":("float","group"),"output":"score","directional":True,"order_preserving":False},
    "group_rightmap":{"factory":"group","inputs":("float","group"),"output":"score","directional":True,"order_preserving":False},

    "ts_delay":{"factory":"ts","inputs":("float","window"),"output":"same","directional":False,"order_preserving":True},
    "ts_delta":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_pct":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_rank":{"factory":"ts","inputs":("float","window"),"output":"rank","directional":False,"order_preserving":False},
    "ts_decay_linear":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_sum":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_prod":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_mean":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_var":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_std":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_ir":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_skew":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_kur":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_min":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_max":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_range":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_argmin":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_argmax":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_median":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_zscore":{"factory":"ts","inputs":("float","window"),"output":"zscore","directional":False,"order_preserving":False},
    "ema1":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ema2":{"factory":"ts","inputs":("float","window"),"output":"score","directional":False,"order_preserving":False},
    "ema3":{"factory":"ts","inputs":("float","alpha"),"output":"score","directional":False,"order_preserving":False},

    "ts_cut_high":{"factory":"condition","inputs":("float","cut_pool","window"),"output":"score","directional":True,"order_preserving":False},
    "ts_cut_low":{"factory":"condition","inputs":("float","cut_pool","window"),"output":"score","directional":True,"order_preserving":False},
    "ts_cut_diff":{"factory":"condition","inputs":("float","cut_pool","window"),"output":"score","directional":True,"order_preserving":False},
    "ts_cut_normdiff":{"factory":"condition","inputs":("float","cut_pool","window"),"output":"score","directional":True,"order_preserving":False},
    "ts_cut_div":{"factory":"condition","inputs":("float","cut_pool","window"),"output":"score","directional":True,"order_preserving":False},
    "adjust_by":{"factory":"condition","inputs":("float","condition","adjust_ratio"),"output":"score","directional":True,"order_preserving":False},
    "reverse_by":{"factory":"condition","inputs":("float","condition"),"output":"score","directional":True,"order_preserving":False},
    "reverse_rank_by":{"factory":"condition","inputs":("float","condition"),"output":"rank","directional":True,"order_preserving":False},
    "trade_when":{"factory":"condition","inputs":("float","condition","quantile"),"output":"score","directional":True,"order_preserving":False},

    "add":{"factory":"cross","inputs":[("rank","rank"),("zscore","zscore")],"output":"score","directional":False,"order_preserving":False},
    "addr":{"factory":"cross","inputs":("float","float"),"output":"rank","directional":False,"order_preserving":False},
    "sub":{"factory":"cross","inputs":[("rank","rank"),("zscore","zscore")],"output":"score","directional":True,"order_preserving":False},
    "subr":{"factory":"cross","inputs":("float","float"),"output":"rank","directional":False,"order_preserving":False},
    "mul":{"factory":"cross","inputs":("float","float"),"output":"score","directional":False,"order_preserving":False},
    "mulr":{"factory":"cross","inputs":("float","float"),"output":"score","directional":False,"order_preserving":False},
    "mulz":{"factory":"cross","inputs":("float","float"),"output":"score","directional":False,"order_preserving":False},
    "div":{"factory":"cross","inputs":("float","float"),"output":"score","directional":True,"order_preserving":False},
    "safe_div":{"factory":"cross","inputs":("float","float"),"output":"score","directional":True,"order_preserving":False},
    "maximum":{"factory":"cross","inputs":("float","float"),"output":"score","directional":False,"order_preserving":False},
    "maximumr":{"factory":"cross","inputs":("float","float"),"output":"rank","directional":False,"order_preserving":False},
    "minimum":{"factory":"cross","inputs":("float","float"),"output":"score","directional":False,"order_preserving":False},
    "minimumr":{"factory":"cross","inputs":("float","float"),"output":"rank","directional":False,"order_preserving":False},
    "mix":{"factory":"cross","inputs":("float","float"),"output":"score","directional":False,"order_preserving":False},
    "fd":{"factory":"cross","inputs":("float","float","window","fd_weight","fd_weight","fd_weight","fd_weight","fd_method"),"output":"score","directional":True,"order_preserving":False},
    "ts_corr":{"factory":"cross","inputs":("float","float","window"),"output":"score","directional":False,"order_preserving":False},
    "ts_reg":{"factory":"cross","inputs":("float","float","window","rettype"),"output":"score","directional":True,"order_preserving":False},
    "cs_reg":{"factory":"cross","inputs":("float","float","rettype"),"output":"score","directional":True,"order_preserving":False},
    "if_else":{"factory":"cross","inputs":("float","float","condition"),"output":"score","directional":False,"order_preserving":False},
}

